service: serverless-example

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  region: ap-southeast-1
  profile: default
  deploymentMethod: direct
  deploymentBucket: aws-migration-sls-deployment

functions:
  profile:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /profiles/
      - http:
          method: ANY
          path: '/profiles/{any+}'
  product:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /products/
      - http:
          method: ANY
          path: '/products/{any+}'
